### ISSUE TITLE
Key-value filter in deep fails

### ISSUE THREAD

**Issue by brihuega** [freywaid/dotted#7]
Hi!
It would be great if the key-value filter operation could search more than one level deep.

Sample:
```
>>> import dotted
>>> fruits = [{'id': {'name': 'Lemon'}, 'colour': 'Yellow'}, {'id': {'name': 'Apple'}, 'colour': 'Green'}]
>>> dotted.get(fruits, '[colour="Green"][0].id.name')
'Apple'
>>> dotted.get(fruits, '[id.name="Apple"][0].colour')
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/dotted/api.py", line 20, in _parse
    results = grammar.template.parseString(ops, parseAll=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyparsing/util.py", line 376, in _inner
    return fn(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/pyparsing/core.py", line 1216, in parse_string
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '['  (at char 0), (line:1, col:1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.12/site-packages/dotted/api.py", line 124, in get
    ops = parse(key)
          ^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dotted/api.py", line 34, in parse
    return _parse(key)
           ^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/dotted/api.py", line 22, in _parse
    raise ParseError(f'{e.msg} at pos {e.loc}: {repr(e.pstr)}')
dotted.api.ParseError: Expected end of text at pos 0: '[id.name="Apple"][0].colour'
```

I'm using dotted-notation 0.11.0 on Python 3.12.4.

Thank you very much for this great package.
Jose

**Comment by freywaid** [comment]
v0.13.0 support this now
